server:
  port: 6060

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;
    # url: jdbc:h2:C:\programming\db\temp
    # driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      schema-locations: classpath:h2/schema.sql
      data-locations: classpath:h2/data.sql
      encoding: UTF-8
      mode: always
