-- 문제1) 사원들의 이름, 부서번호, 부서명을 출력하라
SELECT e.FIRST_NAME , e.DEPARTMENT_ID, d.DEPARTMENT_NAME 
FROM EMPLOYEES e 
	INNER JOIN DEPARTMENTS d 
	ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;

-- 문제2) 30번 부서의 사원들의 이름,직업,부서명을 출력하라
-- ansi join
SELECT e.FIRST_NAME , j.JOB_TITLE , d.DEPARTMENT_NAME 
FROM EMPLOYEES e 
	INNER JOIN DEPARTMENTS d 
	ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
	INNER JOIN JOBS j 
	ON e.JOB_ID = j.JOB_ID 
WHERE e.DEPARTMENT_ID = 30;
-- oracle join
SELECT e.FIRST_NAME , j.JOB_TITLE , d.DEPARTMENT_NAME 
FROM EMPLOYEES e, DEPARTMENTS d, JOBS j
WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID
	AND e.JOB_ID = j.JOB_ID
	AND e.DEPARTMENT_ID = 30;

-- 문제3) 커미션을 받는 사원의 이름, 직업, 부서번호, 부서명을 출력하라
SELECT e.FIRST_NAME, 
	j.JOB_TITLE , 
	d.DEPARTMENT_ID , 
	d.DEPARTMENT_NAME 
FROM EMPLOYEES e 
	INNER JOIN DEPARTMENTS d 
	ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
	INNER JOIN JOBS j 
	ON e.JOB_ID = j.JOB_ID 
WHERE e.COMMISSION_PCT IS NOT NULL;

-- 문제4) 지역번호 2500 에서 근무하는 사원의 이름, 
-- 직업, 부서번호, 부서명을 출력하라
SELECT e.FIRST_NAME ,
	j.JOB_TITLE ,
	d.DEPARTMENT_ID ,
	d.DEPARTMENT_NAME 
FROM EMPLOYEES e
	INNER JOIN DEPARTMENTS d 
	ON e.DEPARTMENT_ID = d.DEPARTMENT_ID 
	INNER JOIN JOBS j 
	ON e.JOB_ID = j.JOB_ID 
WHERE d.LOCATION_ID = 2500;

-- 문제5) 이름에 A가 들어가는 사원들의 이름과 부서이름을 출력하라
SELECT e.FIRST_NAME , d.DEPARTMENT_NAME 
FROM EMPLOYEES e
	INNER JOIN DEPARTMENTS d 
	ON e.DEPARTMENT_ID = d.DEPARTMENT_ID 
WHERE e.FIRST_NAME LIKE '%A%';
-- 5-1
SELECT LOWER('%A%')
FROM dual;

SELECT e.FIRST_NAME , d.DEPARTMENT_NAME 
FROM EMPLOYEES e
	INNER JOIN DEPARTMENTS d 
	ON e.DEPARTMENT_ID = d.DEPARTMENT_ID 
WHERE LOWER(e.FIRST_NAME) LIKE LOWER('%A%');

-- 문제6) 사원이름과 그 사원의 관리자 이름을 출력하라
SELECT e.FIRST_NAME 사원명 , e2.FIRST_NAME AS 매니저명 
FROM EMPLOYEES e
	JOIN EMPLOYEES e2 
	ON e.MANAGER_ID = e2.EMPLOYEE_ID ;

-- 문제7) 사원이름과 부서명과 월급을 출력하는데 
-- 월급이 3000 이상인 사원을 출력하라
SELECT e.FIRST_NAME , d.DEPARTMENT_NAME, e.SALARY 
FROM EMPLOYEES e
	INNER JOIN DEPARTMENTS d 
	ON e.DEPARTMENT_ID = d.DEPARTMENT_ID 
WHERE SALARY >= 3000;

-- 문제8) TJ 이란 사원보다 늦게 입사한 사원의 이름과 
-- 입사일을 출력하라
SELECT e.FIRST_NAME, e.LAST_NAME , e.HIRE_DATE
FROM EMPLOYEES e 
	INNER JOIN EMPLOYEES e2 
	ON e2.FIRST_NAME = 'TJ'
WHERE e.HIRE_DATE > e2.HIRE_DATE;

-- 문제9) 급여가 3000에서 5000사이인 사원의 이름과 
-- 소속부서명 출력하라
SELECT e.FIRST_NAME, d.DEPARTMENT_NAME 
FROM EMPLOYEES e 
	INNER JOIN DEPARTMENTS d 
	ON e.DEPARTMENT_ID = d.DEPARTMENT_ID 
WHERE e.SALARY BETWEEN 3000 AND 5000;

-- 문제10) ACCOUNTING 부서 소속 사원의 이름과 입사일 출력하라
SELECT e.FIRST_NAME , e.HIRE_DATE 
FROM EMPLOYEES e 
	INNER JOIN DEPARTMENTS d 
	ON e.DEPARTMENT_ID = d.DEPARTMENT_ID 
WHERE d.DEPARTMENT_NAME LIKE 'Accounting';

-- 문제11) 급여가 3000이하인 사원의 이름과 급여, 
-- 근무지를 출력하라
SELECT e.FIRST_NAME , e.SALARY , l.CITY
FROM EMPLOYEES e 
	INNER JOIN DEPARTMENTS d 
	ON e.DEPARTMENT_ID = d.DEPARTMENT_ID 
	INNER JOIN LOCATIONS l 
	ON d.LOCATION_ID = l.LOCATION_ID 
WHERE SALARY <= 3000;








