spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      encoding: UTF-8
      mode: always
      schemaLocations: classpath:h2/schema.sql
      dataLocations: classpath:h2/data.sql

server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  port: 8081
mybatis:
  mapperLocations: classpath:mapper/*_mapper.xml

  # configLocation: classpath:mapper/mybatis_config.xml
